ARM-DOE/EMC2

emc2/core/hydrometeor_info.py, emc2/core/instrument.py, emc2/core/instruments.py, emc2/examples/calc_attenuation.py, emc2/io/__init__.py, emc2/io/load_mie_file.py, emc2/simulator/reflectivity.py, setup.py, tests/test_io.py
Adding in the Mie calculation tables.
TODO: More descriptive labels of quantities awaiting Israel Silber's feedback.
=> Mie calculation tables

emc2/io/load_mie_file.py, tests/test_io.py
Adding more descriptive metadata for Mie parameters from data files.
=> ADD: Descriptive metadata for Mie calculation files

emc2/__init__.py, emc2/core/__init__.py, emc2/core/model.py, emc2/simulator/__init__.py, emc2/simulator/reflectivity.py, emc2/simulator/subcolumn.py, tests/test_attenuation.py, tests/test_io.py, tests/test_model.py, tests/test_reflectivity.py, tests/test_subcolumn_generator.py
I have converted a portion of the subcolumn generator into EMC2. Currently, it will generate the hydrometeor fraction in each subcolumn given a number of subcolumns and a single column of hydrometeor fraction.
=> ADD: Subcolumn generator for hydrometeor fraction.

README.md, README.rst
Adding some meat to readme.rst using the original proposal. Removing readme.md.
=> Readme prettifying.... 

emc2/plotting/subcol_display.py
Here is a small fix to make plotting subcolumns in height coordinates work.
=> FIX: Small fix to make plotting columns in height coordinates work

emc2/plotting/subcol_display.py, emc2/simulator/main.py, emc2/simulator/radar_moments.py, emc2/simulator/subcolumn.py
=> Remove redundant line of code that raised errors; change definition of SD for Ze mean; fix a sigma_d_tot calculation issue

emc2/simulator/radar_moments.py
This issue fixes #27 where EMC^2 was crashing when trying to process a single subcolumn.
=> FIX: Single column error.

emc2/simulator/radar_moments.py
This fixes issue #28, which was caused by inconsistent uses of total_hydrometeor for the sigma_d_tot calculation.
=> FIX: Issues with sigma_d_tot

continuous_integration/environment-3.6.yml, continuous_integration/environment-3.7.yml, continuous_integration/environment-3.8.yml, emc2/__init__.py, emc2/core/model.py, emc2/examples/calc_reflectivity.py, emc2/io/load_mie_file.py, emc2/plotting/subcol_display.py, emc2/scattering/__init__.py, emc2/scattering/mie_scattering.py, emc2/scattering/ref_index.py, emc2/simulator/lidar_moments.py, requirements.txt, tests/test_mie.py
Added the ability to do Mie calculations for microwave wavelengths.
=> ADD: Mie calculator for microwave wavelengths

emc2/core/instrument.py, emc2/core/instruments.py, emc2/core/model.py, emc2/simulator/classification.py, emc2/simulator/lidar_moments.py, emc2/simulator/main.py, emc2/simulator/radar_moments.py, setup.py
Fixing some more issues with PEP8 before releasing 1.0.0
=> STY: Fix more pep8 issues and version 1.0.0

README.rst, doc/source/index.rst, emc2/core/model.py, emc2/simulator/lidar_moments.py, emc2/simulator/radar_moments.py
=> Add input parameter options in preparation for E3SM model subclass implementation

emc2/simulator/main.py, tests/test_mie.py
=> FIX: tests

emc2/core/model.py
(now handling only a single spatial coordinate (rather than lat x lon),
typical to cube-sphere output
=> Fix treatment of spatial output in E3SM

.github/workflows/sphinx.yml, continuous_integration/environment_docs.yml, emc2/__init__.py, setup.py
Trying to fix the Sphinx workflow. It was referring to the wrong location for the doc build (_build instead of build)
=> FIX: Build directory in Sphinx workflow

emc2/__init__.py, setup.py
Changing version to 1.2.2 for release.
=> ADD: Version 1.2.2

emc2/core/model.py, emc2/plotting/subcol_display.py, emc2/simulator/psd.py, emc2/simulator/radar_moments.py, emc2/simulator/subcolumn.py
I've added the fall speed assumptions from NUWRF into EMC^2 and also fixed an issue in the WRF data loader where EMC^2 was not generating radar/lidar observables outside of cloud but in precipitation from WRF files. I have also cleaned up some of the syntax of the code inside the subcolumn generator.
=> ADD: NUWRF fall speed parameterization and fixes to WRF data loading

emc2/core/model.py, emc2/simulator/lidar_moments.py, emc2/simulator/psd.py, emc2/simulator/radar_moments.py
MNT: refactoring of terminal velocity parameterization selection
=> ENH: radiation scheme family and microphysics scheme model attrs 

.github/workflows/antivirus.yml, .github/workflows/codeql.yml, .github/workflows/python-package.yml, .github/workflows/sphinx.yml
=> ENH: Modernize github workflows

CONTRIBUTING.rst, README.rst, continuous_integration/environment_docs.yml, doc/source/index.rst, emc2/core/__init__.py
- Updates to:
1. README.rst
2. Index.rst (documentation landing page)
3. Docs toctree to include all updated components in the API.
- Addition of a contributor's guide
=> Update the EMC² documentation to align with ARM-DOE GitHub organization requirements

emc2/core/model.py, emc2/simulator/subcolumn.py
This update adds the option of reading relative variance data from model output and incorporate it in the subcolumn allocation routine, instead of using a fixed value (1).
=> ENH: Dynamic relative variance in subcolumn q_c allocation.
